define([], function() {
  var strings = {
    "_yMeGkKybrchrRl4dKHORJw": {
      "FormattingBarAlignCenterButtonTitle": "[!!--##Ćȅŋŧěř##--!!]",
      "FormattingBarAlignLeftButtonTitle": "[!!--##Ǻľīģń ľėƒť##--!!]",
      "FormattingBarAlignRightButtonTitle": "[!!--##Ȃłįġņ ŕĩġħŧ##--!!]",
      "FormattingBarBoldButtonTitle": "[!!--##Ɓőłď (Čťŕľ+Ƀ)##--!!]",
      "FormattingBarBulletListButtonTitle": "[!!--##ßůĺľȅţēď ľĩšť##--!!]",
      "FormattingBarClearFormattingButtonTitle": "[!!--##Čłȅăŕ àĺľ ƒŏřmȁţŧĭƞģ##--!!]",
      "FormattingBarConfirmAction": "[!!--##Âćŧĭōŋ {0} ƥėřƒŏŗměď.##--!!]",
      "FormattingBarConfirmActionOnSelection": "[!!--##Ăčţıŏň {0} ƿȅřƒŏřmȅď ŏŉ šěĺěćţēđ ŧęxť: {1}##--!!]",
      "FormattingBarNormalTextButtonTitle": "[!!--##Ņőŗmąĺ ťěxţ##--!!]",
      "FormattingBarHeading2ButtonTitle": "[!!--##Ĥȇăđīńģ 1##--!!]",
      "FormattingBarHeading3ButtonTitle": "[!!--##Ħĕãďıňġ 2##--!!]",
      "FormattingBarHeading4ButtonTitle": "[!!--##Ħěăđĩƞĝ 3##--!!]",
      "FormattingBarQuoteButtonTitle": "[!!--##Ƥűłļ ǫŭŏţȇ##--!!]",
      "FormattingBarItalicButtonTitle": "[!!--##İţãļįč (Ćŧřļ+Ĭ)##--!!]",
      "FormattingBarLinkButtonTitle": "[!!--##Ħŷƥēŗļįńĸ##--!!]",
      "FormattingBarNumberedListButtonTitle": "[!!--##ŊũmƄėŗȅđ łįśť##--!!]",
      "FormattingBarUnderlineButtonTitle": "[!!--##Ũńđȇŕłĭňę (Ċţŕľ+Ū)##--!!]",
      "FormattingBarUnlinkButtonTitle": "[!!--##Řȅmővȇ ľĩŋĸ##--!!]",
      "FormattingBarMoreButtonTitle": "[!!--##Mơŕę##--!!]",
      "UndoButtonTitle": "[!!--##Ŭŋďō (Ĉţŕŀ+Ź)##--!!]",
      "RedoButtonTitle": "[!!--##Ŗĕđŏ (Čťŕł+Ɏ)##--!!]",
      "FormattingBarAccessibleLabel": "[!!--##Ƒơřmâŧťĭņğ##--!!]",
      "LinkDialogErrorNotSupportedLink": "[!!--##Ŧĥĩŝ ļıňƙ ŧɏƿȇ īŝ ńőŧ šųƿƿőŕťęď.##--!!]",
      "LinkDialogTextFieldAriaLabel": "[!!--##ŴěƂ ȁďđŕȅşš ťō ľīƞĸ ţō##--!!]",
      "LinkDialogTextFieldLabel": "[!!--##Ŵȅƃ àđďŕěşş:##--!!]",
      "LinkDialogDisplayTextFieldLabel": "[!!--##Ŧēxţ ţơ đĭŝƥłȁŷ:##--!!]",
      "LinkDialogTitle": "[!!--##Ĭƞśěŕŧ ļįƞķ##--!!]",
      "RichTextEditorAriaLabel": "[!!--##Ţěxŧ ȅđĩŧơŗ. Űšȅ Áļŧ+Ƒ10 ťơ ġő ţơ ťŏőļƄåŗŝ.##--!!]",
      "RichTextEditorTitle": "[!!--##Ţĕxţ ěďįŧŏŗ##--!!]",
      "RichTextEditorIframeTitle": "[!!--##{0} {1}##--!!]",
      "RichTextLinkDialogCancelButtonLabel": "[!!--##Čǻŉčěĺ##--!!]",
      "RichTextLinkDialogSaveButtonLabel": "[!!--##Śąvĕ##--!!]",
      "RichTextNavigationAltF10Keys": "[!!--##{0} {1}##--!!]",
      "TextWebPartPlaceholder": "[!!--##Ŧɏƥę ŷơūŗ ŧěxŧ ħȇřȇ##--!!]",
      "ToolbarNavigationArrowKeys": "[!!--##Ųšė âřŗőŵ ƙēȳś ţơ ŉàvĭģäťĕ ıƞśīđě ţħĕ ţơőľƀàř.##--!!]",
      "ToolbarNavigationTabKeys": "[!!--##Ŭšē ŧåƂ ţŏ śŵįţĉĥ Ƅėŧŵēėŋ ţŏơłɓäřš.##--!!]",
      "ToolbarNavigationShiftTabKey": "[!!--##Ūšė ŝĥĩƒţ + ťâɓ ŧŏ ňąvĭĝȃţė ƃâčķ ţő ťȅxťƃŏx##--!!]",
      "ImagesWithTextNotSupported": "[!!--##Ċáƞ'ŧ ƥãŝŧē ĭmâğĕ ŵīŧħīń ţĕxť, ŧâƃłȅ, ļĭŝť őř mųŀţĩƥłē ĩmäğēŝ āŧ ơƞĉȅ. Ƥłėãŝė ƿàşţĕ ȇăčħ įmåĝė įňđĭvīďųāľľƴ.##--!!]",
      "ImagesInTableNotSupported": "[!!--##Ćàƞ'ŧ ƿǻŝŧȇ ǻň ĩmąġȇ ĩńśĭđȇ ōƒ ǻ ťãƅĺĕ. Ŧŕȳ ƿãšťīŉĝ ţĥė īmāğē ŏŭŧśĩďė ōƒ ţĥę ţȁƂļē.##--!!]",
      "CloseWarningText": "[!!--##Ćłŏŝě ŵąřŉįňġ {0} ##--!!]",
      "LoadingText": "[!!--##Ƥȁşťĭńġ...##--!!]",
      "AddRowAboveText": "[!!--##Ĩńśȅŕť ǻƀŏvę##--!!]",
      "AddRowBelowText": "[!!--##İňŝėřţ ƅėļơŵ##--!!]",
      "DeleteRowText": "[!!--##Ďȇłēťė ŗőŵ##--!!]",
      "AddColumnLeftText": "[!!--##Ĭņşēřŧ ŀȇƒŧ##--!!]",
      "AddColumnRightText": "[!!--##İŉşęŕŧ ŕįģħŧ##--!!]",
      "AddRowAboveShortcutText": "[!!--##{0} (Ĉťŗŀ+Śħīƒť+Ā)##--!!]",
      "AddRowBelowShortcutText": "[!!--##{0} (Čţŗł+Šħıƒŧ+Ź)##--!!]",
      "DeleteRowShortcutText": "[!!--##{0} (Ċťŕł+Šħĩƒţ+Đ)##--!!]",
      "RTESettingsText": "[!!--##Ţēxŧ äńď ťǻƃĺě ƒơŕmäŧťįņğ##--!!]",
      "FontDropDownText": "[!!--##Ƒőńŧ ŝťɏľȅ##--!!]",
      "StrikeThroughButtonLabel": "[!!--##Šťřīĸēťħŕōůğĥ##--!!]",
      "SuperscriptButtonLabel": "[!!--##Śũƥęŕśċřıƿŧ##--!!]",
      "SubscriptButtonLabel": "[!!--##Şŭɓşćřĭƿť##--!!]",
      "ParagraphGroupText": "[!!--##Ƥăŕáģŗǻƥĥ##--!!]",
      "JustifyButtonLabel": "[!!--##ĵůšŧĭƒȳ##--!!]",
      "IncreaseIndentButtonLabel": "[!!--##İŉĉřęãŝĕ ĭņďĕŋţ##--!!]",
      "DecreaseIndentButtonLabel": "[!!--##Đȇĉřęâŝȅ ĭŋďĕŋţ##--!!]",
      "FontSizeDropDownLabel": "[!!--##Ƒōŋţ şıžė##--!!]",
      "TableTitle": "[!!--##Ťäƀŀĕ##--!!]",
      "TableGroupLabel": "[!!--##ŢãƂľě (Ƥŗēvįėŵ)##--!!]",
      "TableGroup": "[!!--##Ţāƅŀĕ##--!!]",
      "TableButtonLabel": "[!!--##İńşēŕť ťãƅŀě##--!!]",
      "InsertAndDeleteGroupLabel": "[!!--##Īņśěřţ ȃŋđ đĕŀęţĕ##--!!]",
      "InsertRowBeforeButtonLabel": "[!!--##Įƞšȇŕŧ ǻƃŏvę##--!!]",
      "InsertRowAfterButtonLabel": "[!!--##Ĩńśȇřť Ƃěŀőŵ##--!!]",
      "InsertColumnLeftButtonLabel": "[!!--##Ĩƞşėŗŧ ŀȅƒŧ##--!!]",
      "InsertColumnRightButtonLabel": "[!!--##Ĭŉşȇřţ ŗīģħť##--!!]",
      "DeleteRowButtonLabel": "[!!--##Đȇľĕŧė řōŵ##--!!]",
      "DeleteColumnButtonLabel": "[!!--##Ɗȇŀȇťė ćŏłũmń##--!!]",
      "DeleteTableButtonLabel": "[!!--##Ɗȇĺĕŧȅ ţǻƃļė##--!!]",
      "FontColorLabel": "[!!--##Ƒőŋţ ćőļơŗ##--!!]",
      "StandardColorLabel": "[!!--##Šťãňđäŗď ċőľőŕś##--!!]",
      "DefaultColorLabel": "[!!--##Àŭťơmȁťĩċ##--!!]",
      "RedDarkLabel": "[!!--##Đãřķ řȇđ##--!!]",
      "RedLabel": "[!!--##Řȇď##--!!]",
      "YellowLabel": "[!!--##Ɏĕľľōŵ##--!!]",
      "GreenLightLabel": "[!!--##Ļĭğĥŧ ġřėȅń##--!!]",
      "GreenLabel": "[!!--##Ġŕěěń##--!!]",
      "GreenDarkLabel": "[!!--##Đãŕƙ ġŕęĕņ##--!!]",
      "BlueLightLabel": "[!!--##Ľįĝĥŧ ɓŀůē##--!!]",
      "BlueLabel": "[!!--##Ƀĺūĕ##--!!]",
      "BlueDarkLabel": "[!!--##Ďȁřĸ ƀľŭė##--!!]",
      "PurpleLabel": "[!!--##Ƥųŗƥļȇ##--!!]",
      "HightlightLabel": "[!!--##Ħīģħŀįğĥť ćŏļŏŕ##--!!]",
      "HightlightColorsLabel": "[!!--##Ħĩģħłĭğĥŧ ċơľơřŝ##--!!]",
      "PinkLabel": "[!!--##Ƥįņķ##--!!]",
      "OrangeLabel": "[!!--##Ơřȁńĝę##--!!]",
      "RemoveHighlightColor": "[!!--##Ńō ċőŀŏŕ##--!!]",
      "HyperlinkGroupLabel": "[!!--##Ħŷƥěŗļįňƙ##--!!]",
      "TealLabel": "[!!--##Ťěåŀ##--!!]",
      "MagentaLabel": "[!!--##Māģȅńŧá##--!!]",
      "AquaLabel": "[!!--##Āǫůä##--!!]",
      "MaroonLabel": "[!!--##Mäŕőŏŋ##--!!]",
      "GoldLabel": "[!!--##Ģōľđ##--!!]",
      "GreyLabel": "[!!--##Ģŗȇƴ##--!!]",
      "DarkGreyLabel": "[!!--##Ɖäřƙ ĝŗēɏ##--!!]",
      "BlackLabel": "[!!--##Ƀľåčķ##--!!]",
      "ThemeColorGroupLabel": "[!!--##Ťħĕmĕ ĉōĺơŕś##--!!]",
      "ThemeDarkerLabel": "[!!--##Ŧħēmȅ ďǻŗƙȇŗ##--!!]",
      "ThemeDarkLabel": "[!!--##Ŧĥěmė ďąŕķ##--!!]",
      "ThemeDarkAltLabel": "[!!--##Ťĥĕmę ďàŗĸ ȃļţȅřƞāťę##--!!]",
      "ThemePrimaryLabel": "[!!--##Ŧĥėmȅ ƥřĩmåŗƴ##--!!]",
      "ThemeSecondaryLabel": "[!!--##Ťĥěmę šēċơńđǻřɏ##--!!]",
      "NeutralDarkLabel": "[!!--##Ņȇũťřâļ ďǻřķ##--!!]",
      "NeutralPrimaryLabel": "[!!--##Ńēŭŧŕåĺ ƿŗįmăřŷ##--!!]",
      "NeutralPrimaryAltLabel": "[!!--##Ńęűţřȁľ ƿřĭmářȳ åĺţȅřƞȃŧė##--!!]",
      "NeutralSecondaryLabel": "[!!--##Ŋėůŧřâł śėĉōńđáŗƴ##--!!]",
      "NeutralTertiaryLabel": "[!!--##Ńęūťŕąľ ťĕřţĭáŗȳ##--!!]",
      "TableStylesGroupLabel": "[!!--##Ŧäƅłĕ şŧƴľěş##--!!]",
      "SimpleTableButtonLabel": "[!!--##Ƥļȃįņ##--!!]",
      "TableWithHeaderBorderLabel": "[!!--##Şũƅţŀė ĥĕãđěŗ##--!!]",
      "TableWithFilledHeaderLabel": "[!!--##Ħėàđęŕ##--!!]",
      "TableWithBandedRowsLabel": "[!!--##Åĺŧēŗŋăŧīŉģ řőŵś##--!!]",
      "TableWithBandedRowsAndColumnsLabel": "[!!--##Ċơłŭmƞ ħęȁđęř##--!!]",
      "SimpleTableButtonThemeLabel": "[!!--##Ŧĥęmę-ćőŀŏřėđ ƿŀȁįń##--!!]",
      "TableWithHeaderBorderThemeLabel": "[!!--##Ťħěmȅ-ċŏłőŗȅď şųƄťĺĕ ħěąďėř##--!!]",
      "TableWithFilledHeaderThemeLabel": "[!!--##Ţħęmě-čőłőŕęđ ĥěāđēŕ##--!!]",
      "TableWithBandedRowsThemeLabel": "[!!--##Ŧĥęmĕ-ćőłōŗĕď äłŧėřńâťīňġ řŏŵş##--!!]",
      "TableWithBandedRowsAndColumnsThemeLabel": "[!!--##Ţħėmė-ċŏĺőřĕď ĉŏļųmƞ ĥěäđėř##--!!]",
      "AlignTableGroupLabel": "[!!--##Ťǻƀļȇ áļīğŋmėņţ##--!!]",
      "AlignTableLeftLabel": "[!!--##Ăļĭģŋ ŧáƃļę ĺȇƒť##--!!]",
      "AlignTableCenterLabel": "[!!--##Àļıġň ŧáƂļē ćȅŉťęŕ##--!!]",
      "AlignTableRightLabel": "[!!--##Ǻŀįġń ťäɓĺȇ ŕıġĥť##--!!]",
      "RTEPagePickerSaveAction": "[!!--##Ţħȅ ľĭŉķ {0} ĩś äđđēđ.##--!!]",
      "RTEPagePickerUnlinkAction": "[!!--##Ťħė ŀĩņƙ {0} ĭş ŕȅmōvĕđ.##--!!]"
    },
    "_jP9TaPNRkCXWU4OplNcN+w": {
      "AriaWebPartOrSectionEnterTemplate": "[!!--##{0}. Ƥŗėŝš Ėńŧėŕ ťơ ńávīġȁŧě ıƞšıđē ŧĥē {1}. Ŵĥēň ĩŋşīđę, ůśĕ Äļŧ+Ƒ10 ťō ğŏ ţō ťōōľƅåř, ūŝȇ Âļŧ+Ƥ ťơ mŏvę ƒōčůš ŧơ ŧħȅ ƿřōƥėŗŧȳ ƥǻŋĕ ąŋđ ūśȇ Ēśĉãƿȇ ťŏ ĕxīŧ ťĥė {1}.  ##--!!]",
      "CanvasZoneAriaGoToToolbar": "[!!--##Ƥŕěşŝ ěńţȇŕ ţő ƒơčũŝ īŉśĩđē ŧħĕ ŵĕɓ ƥąřŧ. Āƒťěŕ ȳőŭ ȁřě ıń ŧħě ŵęƄ ƿáŕť, ƥřĕśś ęśĉäƿę ţŏ ŗęťűŗŉ ťő ţħė ţőōŀƃȃř.##--!!]",
      "CanvasZoneAriaGoToWebPart": "[!!--##Ƥŕęşŝ ėŋťęŕ ţŏ ġơ ťơ ţħē ŵēƂ ƿȁřţ'š ŧơŏłƃäŕ, ȳŏŭ ĉąŋ ŧħęņ ƿŗȅšŝ ěşĉȃƥē ťŏ ŗȇŧűřƞ ħȅřĕ.##--!!]",
      "CanvasZoneAriaWebpartName": "[!!--##{0} ŴȇƂ Ƥáŕť##--!!]",
      "ConfirmationDialogYes": "[!!--##Ɏȅŝ##--!!]",
      "ConfirmationDialogNo": "[!!--##Ńō##--!!]",
      "DeleteZoneConfirmationDialogMessage": "[!!--##Ąŗȅ ƴőų şŭřę ȳơũ ŵãňţ ŧŏ đĕľēţĕ ţħįś šĕčţįơņ ăńđ ēvęřɏťĥıŉġ īŋ ıť?##--!!]",
      "DeleteConfirmationDialogTitle": "[!!--##Đȅľęţę Ċōńƒįřmăţīơň##--!!]",
      "DeleteConfirmationDialogMessage": "[!!--##Âŗě ɏơū šűŗė ɏōŭ ŵǻņť ťơ đĕłęŧę ťĥĩŝ ŵėƅ ƿåŗŧ?##--!!]",
      "TextWebPartPlaceholder": "[!!--##Ţŷƥĕ ɏŏũŕ ŧęxţ ĥěŕē##--!!]",
      "TextWebPartDisplayName": "[!!--##Ŧȇxŧ##--!!]",
      "TextWebpartDescription": "[!!--##Ąđđ âŉđ ƒōřmåŧ ţȇxť.##--!!]",
      "WebpartToolbarConfigButtonTitle": "[!!--##Ęđīţ ŵęƀ ƥȃŗť##--!!]",
      "ZoneToolbarConfigButtonTitle": "[!!--##Ęďįţ śĕĉŧĭŏƞ##--!!]",
      "WebpartToolbarMoveButtonTitle": "[!!--##Mővȅ ŵėƀ ƥãřŧ##--!!]",
      "ZoneToolbarMoveButtonTitle": "[!!--##Mővę šȇćťīŏŉ##--!!]",
      "WebpartToolbarDeleteButtonTitle": "[!!--##Ɖėłȅŧĕ ŵęƂ ƥąŗţ##--!!]",
      "ZoneToolbarDeleteButtonTitle": "[!!--##Ɗȅļęťȅ ŝěċŧĩőŋ##--!!]",
      "ToolbarNavigationArrowKeys": "[!!--##Űšĕ ȃřřŏŵ ķȇɏŝ ŧő ńǻvıġȃţȇ ĭņŝıďȇ ţĥė ťőŏŀƂȁŗ.##--!!]",
      "ToolboxAriaLoadingAlert": "[!!--##Ťħē ťōōĺƂōx ĩś ŀơȁďīŋġ ŵēƄ ƥǻřŧŝ.##--!!]",
      "ToolboxAriaLoadingFinishedAlert": "[!!--##Ţħė ŧőơļƃŏx ƒıņĭšĥȅđ ļŏăđĭŉĝ ŵěƅ ƥąřţś.##--!!]",
      "ToolboxErrorMessage": "[!!--##Ŧħēŕę ŵāŝ ãƞ ěŗřőř ƒȇţćĥīņĝ ťĥě ŵȇƂ ƿåřţŝ. Ɲŏţ ȃľŀ ŵĕƀ ƿàŕťš mȃɏ ɓě ǻvåıļâƂĺė.##--!!]",
      "ToolboxHintTitle": "[!!--##Ăđď à ƞĕŵ ŵȇƄ ƿâŗŧ##--!!]",
      "ToolboxNavigationArrowKeys": "[!!--##{0} Ųŝȇ Ŀĕƒŧ őŕ Ʀįġħŧ ţơ ņåvīģǻťȅ. Ŭśĕ Ĕŉŧĕŗ ŧő ȃđď ţħȇ şȅĺĕčŧēď ŵęƀ ƥăŕť.##--!!]",
      "CanvasItems": "[!!--##{0} ıťęmš ĩŉ ťħȇ ťơōľƀàř.||{0} įŧȇm ıņ ţħȇ ŧơŏľƃář.||{0} ĭťėmŝ ĭŋ ŧħē ťőơľƀäŕ.##--!!]",
      "CanvasItemsInterval": "[!!--##0||1||2-##--!!]",
      "ToolboxSectionHeader": "[!!--##Śėĉťĩŏń ĺãȳōųť##--!!]",
      "ToolboxOneColumnPart": "[!!--##Ơňē ĉōĺűmň##--!!]",
      "ToolboxTwoColumnPart": "[!!--##Ţŵŏ ĉőĺūmňş##--!!]",
      "ToolboxThreeColumnPart": "[!!--##Ťħŕĕĕ čōĺũmńš##--!!]",
      "ToolboxOneThirdRightColumnPart": "[!!--##Ơƞĕ-ŧħĭŕđ ŕĭğĥŧ ĉōľűmń##--!!]",
      "ToolboxOneThirdLeftColumnPart": "[!!--##Ōŋė-ťħīŕď ľėƒŧ ćōĺūmň##--!!]",
      "ToolboxFullWidthColumnPart": "[!!--##Ƒŭļŀ-ŵīďťĥ ċơŀūmŋ##--!!]",
      "ToolboxVerticalColumnPart": "[!!--##***Vēŕŧįčȃľ ĉōľũmƞ##--!!]",
      "ToolboxVerticalColumnToolTipText": "[!!--##***Ĉãŉƞōŧ åďď vȇřťĭčąŀ şȇĉťĭơň ɓėċȁůşě ȅĩŧħěŕ vēřťīĉäļ şēćŧīŏń ōř ƒūŀŀ ŵıđťħ šėćŧĩơņ ãľŕęáďƴ ĕxįŝťş##--!!]",
      "ToolboxFullWidthColumnTooltipText": "[!!--##***Ċāŋƞơŧ ēďįť ƒŭłľ ŵĭđŧħ šęćţĭŏŋ Ƅĕĉãũŝȅ vēŗťĩčăļ šěčťīơń ȇxĩşťś##--!!]",
      "SectionPropertyPaneTitle": "[!!--##Śęċťıŏņ##--!!]",
      "SectionPropertyPaneColumnGroupName": "[!!--##Ŀåɏŏůŧ őƿťıōņş##--!!]",
      "ToolbarSelectZone": "[!!--##Šęļėćŧ śȇċťīőŋ##--!!]",
      "DragIconFallbackRTEText": "[!!--##Ťēxţ##--!!]",
      "DragZoneHandleTitle": "[!!--##Ƥřȅšŝ Ȇŋťĕř ōř Šƥáčȅ ţő ȇńťȇŕ mōvȅ mōđė##--!!]",
      "DragZoneMoveStarted": "[!!--##Ƥŗȅšş ųƥ ȁŕřōŵ ƙȅȳ ţŏ mŏvȇ ůƿ àƞď đōŵŋ ăřŗơŵ ķěƴ ţő mővę ďŏŵņ. Ƥŕȇŝŝ Ȅƞţĕŗ ťơ ĉơńƒįŕm ťħę mơvȅ. Ƥřėśš ėščāƥȅ ţő ćąňċȅĺ ťħĕ mơvě. ##--!!]",
      "DragZoneMoveComplete": "[!!--##Mơvĕď ŵĕƀ ƿãŗŧ ƒřŏm {0} ŧŏ {1}. ##--!!]",
      "DragZoneMoveCompleteZone": "[!!--##Mōvȅđ śȅčťıōƞ ƒřơm {0} ťŏ {1}##--!!]",
      "DragZoneMoveCancelled": "[!!--##Mōvȇ ħăş ɓĕȇń čąńċěłłěđ.##--!!]",
      "DragZoneMoveNotAllowedAriaLabel": "[!!--##Ćąň'ŧ mŏvȅ ãňƴ ƒŭŗţĥėŕ įŉ ŧħāŧ ďĩŕėćţıőń, ŏŕ mơvĕ ĩş ŉőŧ ȃŀľŏŵēđ ţơ ťħąţ śȅĉŧīőņ##--!!]",
      "DragZoneMoveNotAllowed": "[!!--##Mővę ŋőţ ȃłĺōŵēđ##--!!]",
      "DragZoneMoveInsideLevelControl": "[!!--##Ƥơŝįţıōŋ {0}##--!!]",
      "DragZoneMoveInsideLevelSection": "[!!--##Ċơłůmń {0}, ƥơşıţĩŏŉ {1}##--!!]",
      "DragZoneMoveInsideLevelZone": "[!!--##Šęċţĭơń {0}, ċōłũmŋ {1}, ƿōśĭţĭŏŉ {2}##--!!]",
      "WebPartAriaLabel": "[!!--##ŵȅƅ ƿåŗŧ##--!!]",
      "SectionContextualAriaLabel": "[!!--##{0}, {1} ŝēĉţıŏń ċōņťȁĩņĩŋģ {2}##--!!]",
      "SectionAriaLabel": "[!!--##śěċŧīơƞ##--!!]",
      "WebPartsInSectionLabel": "[!!--##{0}, {1}##--!!]",
      "ToolboxHintSectionTitleOnlyLayouts": "[!!--##Āďď ȃ ņȇŵ śĕćŧīőƞ##--!!]",
      "ToolboxHintTitleWithLayout": "[!!--##Ǻďď ã ŉȅŵ ŵȅƅ ƥāřŧ įŋ {0}##--!!]",
      "ToolboxHintColumnOne": "[!!--##čŏľūmň ŏńȇ##--!!]",
      "ToolboxHintColumnTwo": "[!!--##ċơłůmƞ ŧŵơ##--!!]",
      "ToolboxHintColumnThree": "[!!--##ċőĺŭmƞ ŧĥŗȇę##--!!]",
      "EmptySectionAriaLabel": "[!!--##ńő ŵěƅƿåřţ##--!!]",
      "SectionPositionAriaLabel": "[!!--##Şęċŧıŏƞ {0} ŏƒ {1}##--!!]",
      "CloseButtonAriaLabel": "[!!--##Čŀōśě##--!!]",
      "DeleteConfirmationLabel": "[!!--##{0} ħåś ƃěēń ďĕļěţĕď.##--!!]",
      "NarrowModeDialogTitle": "[!!--##Ŵįďēň ȳŏūŕ Ƃŗŏŵšĕŗ ŵĩńđōŵ##--!!]",
      "NarrowModeDialogSubtitle": "[!!--##Ėďĭťįƞġ īş ƞơť ăvāīľàƃłě ıƞ ă ŉȁŗřơŵ Ƅřōŵŝȅř ŵīńďōŵ. Mäķę ťĥȇ ŵīņďơŵ ŵīďęŕ ŧŏ ćŏƞţıńŭě ȇďĩţĭŋĝ.##--!!]",
      "DialogDescription": "[!!--##{0} ďīǻľōģ {1}##--!!]",
      "SectionBackgroundPropertyColumnGroupName": "[!!--##Şęċţĩőň ƅâćƙğŗōųƞď##--!!]",
      "SectionBackgroundNeutralButtonLabel": "[!!--##Ňěůţŕáľ##--!!]",
      "SectionBackgroundSoftButtonLabel": "[!!--##Ŝōƒŧ##--!!]",
      "SectionBackgroundStrongButtonLabel": "[!!--##Şťŗŏƞĝ##--!!]",
      "SectionBackgroundNoneButtonLabel": "[!!--##Ņơŉĕ##--!!]",
      "CanvasVerticalSectionZoneLabel": "[!!--##***Vėŕťĭĉãļ Ŝėċŧįōň 1 ŏƒ 1##--!!]",
      "ToolbarDuplicateTitle": "[!!--##Ɖųƿŀĭčãţę ƥȃřţ##--!!]",
      "YammerHighlightsWebpartTitle": "[!!--##Ĥīĝĥļĩĝħťş##--!!]"
    },
    "_O6tJrUs6NrlW91qKLBlc7g": {
      "loadingText": "[!!--##Ľōąđıŋġ…##--!!]",
      "relevantPeopleHeaderText": "[!!--##Ƥĕőƿļė ŷŏű ŵőŕķ ŵĩţħ##--!!]",
      "noResultsFoundText": "[!!--##Ŵē đĭďŋ'ŧ ƒıňď ąŉɏ mȃţĉĥěş##--!!]",
      "suggestionsAvailableAlertText": "[!!--##Śųģğēŝţıơņš ăvȃıļåƃłȇ##--!!]",
      "suggestionsContainerAriaLabel": "[!!--##Şůĝġĕŝŧėď čơŉťäčŧŝ##--!!]",
      "suggestionsHeaderText": "[!!--##Śŭĝġēŝŧĩōƞş##--!!]",
      "moreCharactersText": "[!!--##Ěŉţȅř mőřē ćĥǻŕąćŧęŗś##--!!]",
      "noPermissionText": "[!!--##{0} ďōĕś ńơŧ ħàvȅ ƥēřmĩśśĩŏň ŧō ţħĭś ƿäġȅ, śō ŵıłĺ ňōţ ƅĕ ńőťįƒįėď âƅơůť ɏōűŗ ćŏmmĕńŧ.##--!!]",
      "mentionLink": "[!!--##@{0}##--!!]",
      "teachingBubbleHeadline": "[!!--##@Mĕńťįōŉ##--!!]",
      "teachingBubbleContent": "[!!--##Ȳōų čáŉ @mēŉťĭōƞ ƥęőƥľȇ įƞ ĉŏmměƞťś ŵħȇņ ƴōŭ ŵȁņť ţő ģėŧ ţĥȇīŕ âťŧȇŋţīơƞ. ĵŭśť ťɏƥė ŧħē @ ŝƴmƂŏĺ Ƃȅƒōŕě ä ŋåmȇ ťō ğěŧ šţáŗţěď!##--!!]",
      "mentionPlaceholderText": "[!!--##{0}. Ţŷƥē @ ŧō mȇŉťĭōň śŏmėơňĕ##--!!]",
      "CloseButtonAriaLabel": "[!!--##Ĉĺŏŝĕ##--!!]",
      "searchDirectory": "[!!--##Ŝěãřċħ ďĩŕěčŧơŕŷ##--!!]",
      "mentionAlertMessage": "[!!--##Mėƞţĭőń ǻďđėđ ƒŏŗ {0}##--!!]"
    },
    "_/GZrHjuQO4erDQbBRI2XSA": {
      "DialogTitle": "[!!--##Ĭŋšȅŗť ŀıňĸ##--!!]",
      "UrlTextFieldLabel": "[!!--##Âďđŗęšš##--!!]",
      "UrlTextFieldAriaLabel": "[!!--##ŴȇƂ äđďŗęśś ŧō ŀĭŉƙ ţō##--!!]",
      "UrlTextFieldError": "[!!--##Ŧħĭş ŀĩņƙ ťɏƥě īś ņơť śűƿƥōřťĕď.##--!!]",
      "TitleTextFieldLabel": "[!!--##Ţĕxţ ťő đĩśƿľäŷ##--!!]",
      "RecentPagesLabel": "[!!--##Mōšŧ řěćėŋť ƿáģēš őň ŧħĩš šīťȇ##--!!]",
      "SearchForPagesLabel": "[!!--##Ƥáģěŝ ōŋ ţĥĭŝ ŝıŧě ťĥȁţ māŧčħ ƴōųŕ šēāŕċħ##--!!]",
      "RecentSpacesLabel": "[!!--##***Mőşţ ŗęčěňť şƥāċěŝ őň ŧħįš ŝīŧȇ##--!!]",
      "SearchForSpacesLabel": "[!!--##***Šƥąĉěŝ ơň ťħıś šĭţė ŧħȁť măŧčħ ȳơűř śęąŕċħ##--!!]",
      "NoResultLabel": "[!!--##Ńő ĭťěmš màŧčĥ ȳōūŕ şēȃřčĥ##--!!]",
      "TryAgainLabel": "[!!--##Ŧŗŷ ȃ đīƒƒĕŕĕńŧ ĸȅɏŵŏŗď##--!!]",
      "OpenLinkInNewTabLabel": "[!!--##Ơƥěň ĺıƞĸ īņ ȃ ŉȇŵ ŧáƄ##--!!]",
      "SaveButtonLabel": "[!!--##Ŝǻvȇ##--!!]",
      "CancelButtonLabel": "[!!--##Ćāŋĉȇł##--!!]",
      "UnlinkButtonLabel": "[!!--##Ŗėmōvȅ ľĩŉķ##--!!]",
      "TitleSuggestionsColumnName": "[!!--##Ťĩŧłȅ##--!!]",
      "EditorSuggestionsColumnName": "[!!--##Mŏďıƒıēđ Ƅŷ##--!!]",
      "ModifiedSuggestionsColumnName": "[!!--##Mōďĩƒįȅđ##--!!]",
      "PageContentContainsSearchText": "[!!--##\"{0}\" ƒơūŉđ ĩŉ ƥáĝē čơņťȅńŧś##--!!]",
      "CurrentPage": "[!!--##(ćŭŗŗēŋť ƥȃġȅ)##--!!]",
      "SearchTextFieldLabel": "[!!--##Šĕăŗćħ##--!!]",
      "SearchPagesTextFieldPlaceholder": "[!!--##Ěŉťēŗ ƙȇƴŵơŕđš ťŏ ŝĕàŗċħ ƒőŗ ƥäġęš őň ŧĥıś šıŧȇ##--!!]",
      "SearchSpacesTextFieldPlaceholder": "[!!--##***Ȇņţęŗ ķėƴŵŏřďş ťŏ śĕāŕċħ ƒơŗ şƥăčėş ŏń ţħįş šįţę##--!!]",
      "DialogAriaDescription": "[!!--##Įŋśĕŕť ȃ ŀīŉƙ ťő å ƥãğĕ őŋ ţħě čųřŗėńť šıŧĕ ơŕ ţŏ ȃ ƿãĝȇ ơƞ ăƞōţĥĕŕ śīťȅ.##--!!]",
      "SuggestionsListAriaLabel": "[!!--##Ŝēĺėčŧ à ƥäġȇ ƒřōm ţħȇ {0} ļıŝţ. Ƥŗęśŝ ţħě Űƿ ãŋđ Ɗőŵň ǻŕŗőŵ ķĕƴŝ ťơ ňåvĭğàţě ťħŗŏůĝħ ŧĥė ƥāĝĕŝ. Ƥŗěşš ŧħĕ Şƿȃčě ƙēŷ ŧŏ şȅłėćţ ȃ ƥȃğȅ. Ŵĥȅń â ƿąğē ıš şēĺȇĉŧȇď, ţħē ƥăĝȅ ĺĭńķ ŵĩľľ ƅȅ ŭşęđ įņ ţħě Ŀĭŉĸ ĩńƥũţ ƀơx, ȁƞđ, ĭƒ ŧĥȇŗė ĩş ňō ţěxţ ĩŉ ţĥĕ Ŧĕxţ ťơ ďīśƿľȃŷ ĭńƥūť Ƃơx, ťĥě ƿãģȅ ţıťĺȅ ŵĭĺľ ƀė ůśēđ.##--!!]",
      "SaveButtonDisabledScreenReaderAlert": "[!!--##Ťħę Şâvē Ƅūťťőƞ ıš ňőŧ ävâĩŀăƄļȇ Ƃĕćåűšė åƞ ĭŋvȁľĭđ ŵėɓ ąďđŕęšŝ ŵàš ȇńţęřęđ.##--!!]",
      "SaveButtonEnabledScreenReaderAlert": "[!!--##Ŧĥĕ Ŝävę ƀůťťōń ĭŝ àvāıłäƅľė.##--!!]",
      "PageIsSelectedScreenReaderAlert": "[!!--##Ŧħē ƿäģȇ {0} ĭś şĕŀĕčŧēď.##--!!]",
      "IsSearching": "[!!--##Śȅâřċħıńĝ...##--!!]",
      "SearchResultsShowing": "[!!--##Śēãŗċħ řĕŝűļŧŝ ăřě ďışƿŀáŷȇď. Ƥŕĕşś Ţȁƀ ţō ġơ ţő ťħē Şēăŕčĥ ŕȇşũļŧş ĺīśť.##--!!]",
      "RecentPagesShowing": "[!!--##Å łīşť ơƒ ŕȇčęƞŧ ƥǻġėŝ ĩś đĩŝƿľåŷȇď. Ƥŗěśš ŦáƄ ŧō ģō ŧő ŧħę Ŗĕćęňţ ƥāğėś ĺĭšţ.##--!!]"
    },
    "_4SOrKBlkyRLkXWcT6txoow": {
      "ToolboxSearchAccessibleLabelTemplate": "[!!--##Ťȳƥȇ ĥȅŕȅ ťő ŝęăŗċĥ ƒōŕ á ŵęƂ ƥăŕţ. {0}##--!!]",
      "ToolboxSearchEscapeAccessibleLabel": "[!!--##Ƥřēśś Ěşčȁƥĕ ŧő čĺȇǻŗ ţħę ėxĩšŧīŋġ ŝęąřċĥ.##--!!]",
      "ToolboxSearchLabel": "[!!--##Šęàřċħ##--!!]"
    },
    "_NS+5Kf9zpnH1/LStsp+Tfw": {
      "ToolboxCategoryTextMediaAndContent": "[!!--##Ţěxţ, mȅďıã, ăŉđ ćŏňťȅňť##--!!]",
      "ToolboxCategoryDiscovery": "[!!--##Đĩśćővėŕɏ##--!!]",
      "ToolboxCategoryCommunicationAndCollaboration": "[!!--##Ĉơmmũňĭĉăťīŏń ȁńď ćōľłāɓőřāťĭơŉ##--!!]",
      "ToolboxCategoryPlanningAndProcess": "[!!--##Ƥłȁŋŉıņġ āńď ƥřőčȇşś##--!!]",
      "ToolboxCategoryBusinessIntelligence": "[!!--##Ɓũśĩƞěşš ãƞđ ĭňťēľľįĝěŋĉę##--!!]",
      "ToolboxCategorySiteTools": "[!!--##Šıŧė ťőŏĺš##--!!]",
      "ToolboxCategoryConnectors": "[!!--##Ćŏƞńȅćŧōŗś##--!!]",
      "ToolboxCategoryOther": "[!!--##Ơťĥēŕ##--!!]",
      "ToolboxGroupNameFeatured": "[!!--##Ƒęąţũřęđ##--!!]",
      "ToolboxGroupNameAlphabetical": "[!!--##Ăłł Ǻ ţō Ƶ##--!!]"
    },
    "_RRzf46hnc4+fBX8RHyocNg": {
      "TextWebPartDisplayName": "[!!--##Ţȅxŧ##--!!]",
      "TextWebpartDescription": "[!!--##Åđď ăŋď ƒŏŕmǻŧ ţėxţ##--!!]"
    },
    "_6tOZemhV08aF1IgNDNeiwQ": {
      "ToolboxGroupNameFullWidth": "[!!--##Ɏơŭ čăƞ âđď ơńę ŏƒ ťħěšȅ ŵȇƀ ƥȃŗŧš ŧő ťħıŝ ƒűĺŀ-ŵıďţĥ čőĺůmŋ##--!!]"
    },
    "_2TT4IG31kAjRqhD0h5kPOg": {
      "ToolboxGroupSeeAllButtonLabel": "[!!--##Śĕė äŀŀ##--!!]",
      "ToolboxGroupSeeAllButtonAriaLabel": "[!!--##Šęĕ ǻļŀ ŵėƅ ƿăŗţŝ ıŋ {0}.##--!!]",
      "ToolboxGroupAriaLabel": "[!!--##{0} łışť. Ůşę ŀėƒţ ąňđ řĭğĥŧ āŕřơŵ ķėƴş ţő mővē ŵīţħīň ŧħĕ ļīśţ.##--!!]"
    },
    "_WVn4QXYnL8WpGCqr2C9ySA": {
      "ToolboxCategoryAllCategory": "[!!--##Ąłł ƀƴ ċāťȇğőŕȳ##--!!]",
      "ToolboxCategorySortingCategory": "[!!--##Ąļļ Ǻ ŧő Ž##--!!]",
      "ToolboxCategorySearchResults": "[!!--##Šȅāŕčĥ ŗĕšŭļţś##--!!]",
      "ToolboxCollapseButtonDescription": "[!!--##Řȇšţŏŕę ťơ őŕıġīńáŀ šīžē##--!!]",
      "NoResultLabel": "[!!--##Ňō ĭťėmś màţĉĥ ȳŏűř şėāřĉĥ##--!!]",
      "TryAgainLabel": "[!!--##Ŧřŷ ă ďıƒƒȅŕěňŧ ķěƴŵŏŕď##--!!]",
      "LargeToolboxAriaTitle": "[!!--##Ěxƥąŉďēď ŵȅƃ ƥåŗţ ťŏŏļƄōx.##--!!]",
      "LargeToolboxAriaSubTitle": "[!!--##Ťĥėŕē ȃřȇ {0} ĩŧēmś ĭń ŧħē ŧŏŏļɓōx.||Ťĥĕŗě ǻŗę {0} īţĕm ĩŋ ţĥė ŧőōļƃŏx.||Ŧħėřȇ āŕȇ {0} ıţėmś ĩŉ ţĥė ŧōőłƃōx.##--!!]",
      "ToolboxCollapseButtonAriaLabel": "[!!--##Ĉőłĺåƿšę.##--!!]",
      "CountStringIntervals": "[!!--##0||1||2-##--!!]",
      "DropDownMenuAriaLabel": "[!!--##Ŝĥōŵıńğ ŵȇƃ ƥāŕŧš ƒŗőm {0} čåţēġŏřŷ.##--!!]",
      "SwitchCategoryAlert": "[!!--##Ćĥȃňġȅď ŧō {0}.##--!!]",
      "BackButtonAriaLabel": "[!!--##Ĝő Ƃâčķ ŧơ ţĥȅ ƿřȅvīŏűš vĭĕŵ.##--!!]"
    },
    "_CZsUWMvZilAKKAfwQSdzKQ": {
      "ToolboxExpandButtonTitle": "[!!--##Ēxƿăńđ ťơ šěė mōŗȅ ŵȇƄ ƥǻŗŧş##--!!]",
      "ToolboxNoItemsFound": "[!!--##Ŵĕ ċŏűłđŋ'ţ ƒĩņď ãņŷŧĥįņģ ťĥàŧ màţčħėš ɏōůŕ şȇȁŕċĥ.##--!!]",
      "ToolboxSectionHeader": "[!!--##Śȅĉţĩŏŉ ĺàŷōůţ##--!!]",
      "CanvasItems": "[!!--##{0} ŵěƃ ƥăřţş đĭŝƥļáȳēď ĭņ ţħȇ ţơŏľƂơx.||{0} ŵĕƅ ƿàŕť đįŝƥĺåɏěď īŋ ťħȇ ťőōŀƄŏx.||{0} ŵęƀ ƿäŕťś ďįŝƥĺâŷĕď īň ŧĥĕ ťōŏŀƃơx.##--!!]",
      "CanvasItemsInterval": "[!!--##0||1||2-##--!!]"
    },
    "_NAR8NFw8cblGJm9t5CjqOw": {
      "SuccessfullyLoadedText": "[!!--##Şűċćęşşƒũŀĺȳ łŏāďĕď ďȇƄűġ mâňįƒėŝţś.##--!!]",
      "ErrorLoadingText": "[!!--##Ƒāĩļĕď ţŏ ŀơȁđ đěƃůģ mäňĭƒēşťš: {0}##--!!]"
    },
    "_vd/LT/qfiQhbHFfeM1GtlA": {
      "FetchFailedError": "[!!--##***Ƒėŧćĥıŉġ ŵȅƂƥāťš ƒåīŀȇđ ŵīťĥ ēŗřőř \"{0}\". Řēņďȇŗ ŏƒ â ćąćħēď ŵŏŕƙƃȅƞċĥ måɏ ƒåıľ.##--!!]"
    },
    "_FQya7ZjwIyrOEutOa+omIA": {
      "Title": "[!!--##Ŵāřŉįņġ##--!!]",
      "SubText": "[!!--##Ƴōũŗ ŵěƀ ƥåŗŧ ŵĩłĺ ƞơť àƥƥȅäŕ ıń ţĥē ťŏơŀƄơx. Ƥļȇāşȇ måķė ŝűřě \"ģűľƥ šȅŕvę\" įş řůŋŋĩńĝ ĭň á ŵȇƅ ƿáŗţ ƿŗōĴȇĉŧ. Ƥļěâśě ŕěƒřĕşĥ ťħȇ ƿȃğē ŏņćě \"ğűľƥ šȇŕvĕ\" ĩš ŗűŉņĭňġ.##--!!]",
      "OkButtonText": "[!!--##ŐĶ##--!!]",
      "ClickHerePrefix": "[!!--##Ċłīċķ ##--!!]",
      "ClickHereLink": "[!!--##ĥėŕē##--!!]",
      "ClickHereSuffix": "[!!--## ƒōř mőřė īňƒōřmāŧĭơŉ.##--!!]"
    },
    "_1JArBGDet5Uj9pJOV/9sFw": {
      "UrlTextBoxPlaceholder": "[!!--##Ēŉţěŗ à ŮŖĹ ťő vıēŵ ĩň Mőɓĩľě Ƥřĕvĭȅŵ Ŧơŏŀ.##--!!]",
      "ScreenReaderMobilePreviewEntered": "[!!--##Ÿŏū ħǻvė ēŉŧĕŕėď ŧħȇ Mŏƃīļě Ƥŕęvıȅŵ Ţŏőŀ. İƒ ɏőų ŵàņţ ťŏ ƿŕȅvįēŵ à ďīƒƒĕŗȅŋť ƥàĝē, ęŋŧȅŗ ţħĕ ŨŔŁ īŋ ŨŔĽ ťěxŧ ƒĭȅŀď. Ŧŏ ćļőšē ţĥę ŧōőļ ăňď ğŏ ƅâċķ ŧŏ Ŵŏřƙƃěŋċĥ, ƥřěşś Ęśĉąƿē.##--!!]",
      "ScreenReaderDevicePickerEntered": "[!!--##Ũśę ĺęƒţ âŉď řīĝħŧ âřřōŵ ķėƴŝ ŧō čħōőşė ă ďĕvįčȇ ťő ċĥąŉģę ţħē ƥŕȇvīēŵ ščŕėĕƞ şīƶę.##--!!]",
      "ScreenReaderDevicePickerSelectionChanged": "[!!--##Ƥŕȇšş Ȅņŧęř ţō ĉĥơōŝȇ ŧħĩş đęvĭċę.##--!!]",
      "Width": "[!!--##Ŵıđŧĥ##--!!]",
      "Height": "[!!--##Ĥēįģħŧ##--!!]"
    },
    "_8EVKOH1av6NjR/ZNfdafrw": {
      "WebPartData": "[!!--##***ŴȇƄ Ƥąŗŧ Đåťâ##--!!]",
      "ClassicPages": "[!!--##Čľáśśĩč Ƥäģěŝ##--!!]",
      "ModernPages": "[!!--##Mơďĕŗņ Ƥăġĕŝ##--!!]",
      "Close": "[!!--##Čłŏśė##--!!]",
      "WebPartDataHelpInfoLink": "[!!--##***Ĺēãŗń åƀŏųţ ƥŗŏvĩśĭōņįňģ ŜĥąřěƤơįŋť âşŝēţś ƒřōm ŷŏűř ŠħăŕěƤōįŉŧ ĉŀĩȅňŧ-śĭďė ŵĕƂ ƿåŗŧ##--!!]"
    },
    "_IusqdbcSoVYQiit3+QRSxw": {
      "Office365Title": "[!!--##Őƒƒĩċē 365##--!!]",
      "SharePointWorkbenchTitle": "[!!--##ŚħȁŗēƤőīŋť Ŵőřƙƅēňčħ##--!!]",
      "ScreenReaderDisplayModeSwitchToEditMode": "[!!--##Şŵĭŧćĥȇď ƒŗōm ƥŕěvĩĕŵ mőđĕ ţơ ēđĭŧ mōďȅ.##--!!]",
      "ScreenReaderDisplayModeSwitchToReadMode": "[!!--##Šŵĩŧċħēď ƒřőm ȅďīŧ mŏđȇ ťŏ ƥŕĕvĩėŵ mŏđě.##--!!]"
    },
    "_nCtJlVOXBHa59LgYtajnjA": {
      "Save": "[!!--##Ŝąvę##--!!]",
      "SaveAltText": "[!!--##Űšě ŧō ŝąvē ţħę ĉůŗŕęńť ŵŏŗƙƀȇņĉħ şŧǻţė.##--!!]",
      "Discard": "[!!--##Ďīśċǻřđ##--!!]",
      "DiscardAltText": "[!!--##Ŭśȇ ŧō đįśĉäŕď ŧħě ċűŗřęƞŧ ŵŏŗĸƄȅŋčĥ ŝţȃŧē.##--!!]",
      "Mobile": "[!!--##Mŏƀĭŀě##--!!]",
      "MobleAltText": "[!!--##Ůŝę ŧŏ ơƿėƞ ţĥȅ mőƀĩľė ƥŕėvĭěŵ ţơōľ ƒőŗ ä čȇŀł ƿħơƞę.##--!!]",
      "Tablet": "[!!--##ŦǻƄļėţ##--!!]",
      "TabletAltText": "[!!--##Űšȅ ţő ŏƿȅń ţĥę mōƃīļė ƥŕėvıěŵ ťŏőľ ƒơŗ ä ťăƄľȅť.##--!!]",
      "Preview": "[!!--##Ƥŗēvĭėŵ##--!!]",
      "PreviewAltText": "[!!--##Ūŝĕ ŧŏ ŝŵĭŧċħ ƒŕőm ȅďıţ mőďȅ ťő ƿŕȇvĭȅŵ mŏďȇ.##--!!]",
      "Edit": "[!!--##Ěđıţ##--!!]",
      "EditAltText": "[!!--##Ŭşė ţō śŵīţćħ ţŏ ėđıť mŏđȅ.##--!!]",
      "WebPartData": "[!!--##***ŴȅƄ ƥãŕţ ďâŧă##--!!]",
      "WebPartDataAltText": "[!!--##***Ɗĭśƿľåƴ ŧħĕ ŝēŗĩāłįžĕđ ŵȇƄ ƿáŗŧ đãťă.##--!!]"
    }
  };

  strings.default = strings;
  return strings;
});