define([], function() {
  var strings = {
    "_yMeGkKybrchrRl4dKHORJw": {
      "FormattingBarAlignCenterButtonTitle": "Ċȅƞťĕř",
      "FormattingBarAlignLeftButtonTitle": "Ǻŀĩġń ŀęƒŧ",
      "FormattingBarAlignRightButtonTitle": "Âļįģƞ řıġħţ",
      "FormattingBarBoldButtonTitle": "ʙōĺđ (Ċŧŕļ+Ɓ)",
      "FormattingBarBulletListButtonTitle": "ßűļŀėţěđ ĺĩşţ",
      "FormattingBarClearFormattingButtonTitle": "Ċŀȇāŗ ǻłļ ƒŏŕmâťŧĩňģ",
      "FormattingBarConfirmAction": "Äčŧĩőƞ {0} ƥēŕƒőŕměď.",
      "FormattingBarConfirmActionOnSelection": "Ȁćŧĭōŉ {0} ƿėŕƒŏŗmēđ őŋ ŝĕłȇċťėđ ŧĕxť: {1}",
      "FormattingBarNormalTextButtonTitle": "Ŋōŕmâľ ťěxŧ",
      "FormattingBarHeading2ButtonTitle": "Ĥēǻďĩńĝ 1",
      "FormattingBarHeading3ButtonTitle": "Ħȅăďīņĝ 2",
      "FormattingBarHeading4ButtonTitle": "Ħěăďĩŉĝ 3",
      "FormattingBarQuoteButtonTitle": "Ƥűľĺ ǫűơťē",
      "FormattingBarItalicButtonTitle": "Īťāłĭĉ (Ċţřł+Ĭ)",
      "FormattingBarLinkButtonTitle": "Ħŷƥěŗĺįŉƙ",
      "FormattingBarNumberedListButtonTitle": "Ńųmƀĕŕęď ŀįśŧ",
      "FormattingBarUnderlineButtonTitle": "Ųŉđȅŗŀįƞȅ (Čŧřŀ+Ū)",
      "FormattingBarUnlinkButtonTitle": "Ŕęmővė łĭňƙ",
      "FormattingBarMoreButtonTitle": "Mőŕě",
      "UndoButtonTitle": "Ŭņďơ (Ċŧŗŀ+Ż)",
      "RedoButtonTitle": "Ŕēďō (Ćŧŕł+Ɏ)",
      "FormattingBarAccessibleLabel": "Ƒơŗmāťŧīńġ",
      "LinkDialogErrorNotSupportedLink": "Ŧĥĩş ŀįňĸ ţŷƿē ĩš ņŏţ śůƿƥŏŗŧĕđ.",
      "LinkDialogTextFieldAriaLabel": "Ŵȅƀ ãďđŗĕşš ŧŏ ľīŋƙ ťō",
      "LinkDialogTextFieldLabel": "Ŵȇƀ åđđŗęšŝ:",
      "LinkDialogDisplayTextFieldLabel": "Ťȇxŧ ťơ ďĭšƥŀąɏ:",
      "LinkDialogTitle": "İŋşȇŗť łıŋƙ",
      "RichTextEditorAriaLabel": "Ţęxţ ėďıŧőŗ. Ūŝě Ȃĺť+Ƒ10 ťő ģŏ ťő ŧŏơŀƅäŕš.",
      "RichTextEditorTitle": "Ţĕxţ ęđĭŧőŕ",
      "RichTextEditorIframeTitle": "{0} {1}",
      "RichTextLinkDialogCancelButtonLabel": "Čãƞćȇŀ",
      "RichTextLinkDialogSaveButtonLabel": "Šàvě",
      "RichTextNavigationAltF10Keys": "{0} {1}",
      "TextWebPartPlaceholder": "Ţŷƿę ɏơůŗ ţȇxţ ħēřē",
      "ToolbarNavigationArrowKeys": "Űŝė ąŗřơŵ ƙĕƴŝ ŧơ ńävĭğȃťĕ īƞşĩďȇ ŧħę ţōőŀƂâŕ.",
      "ToolbarNavigationTabKeys": "Ūŝȅ ţȃƅ ţŏ ŝŵĩţćħ ɓėţŵĕěń ťōŏŀƅȃŗş.",
      "ToolbarNavigationShiftTabKey": "Ŭšę śĥīƒŧ + ŧȁƂ ťő ŋąvīġǻťė ɓǻĉķ ŧŏ ŧĕxťƂŏx",
      "ImagesWithTextNotSupported": "Čāƞ'ţ ƥåşťȅ ımàĝě ŵıťĥĩņ ťēxţ, ţǻƄļȅ, ŀīŝŧ ơŕ mųłţıƥĺę įmåġęŝ ąť ōňċě. Ƥļėăşȇ ƥāŝţė ȇāćĥ īmāĝē ĩƞďĭvĩďŭąŀļŷ.",
      "ImagesInTableNotSupported": "Ćǻň'ţ ƿąŝŧė ãƞ īmāģě īńšįďė ŏƒ ǻ ŧǻƀĺȇ. Ťŗȳ ƿāśŧīňģ ťĥĕ ĩmåğė ōŭŧŝıđē ŏƒ ťĥę ťąƅĺė.",
      "CloseWarningText": "Čŀōśĕ ŵǻŗŉīńĝ {0} ",
      "LoadingText": "Ƥãšŧĩŋğ...",
      "AddRowAboveText": "Īňšȅŕţ åƅōvě",
      "AddRowBelowText": "Ĩņšȇřţ ƀȅľōŵ",
      "DeleteRowText": "Ɗēłĕţē ŗơŵ",
      "AddColumnLeftText": "İňŝėŕţ ŀėƒŧ",
      "AddColumnRightText": "Įńšēŗť ŗĭġĥţ",
      "AddRowAboveShortcutText": "{0} (Čţŕł+Ŝħįƒť+Å)",
      "AddRowBelowShortcutText": "{0} (Ĉţŗľ+Ŝĥīƒť+Ž)",
      "DeleteRowShortcutText": "{0} (Ĉťřļ+Śħĭƒť+Ď)",
      "RTESettingsText": "Ţęxŧ áňđ ţāƀŀė ƒŏŗmâŧţĩńģ",
      "FontDropDownText": "Ƒőƞť śţƴŀē",
      "StrikeThroughButtonLabel": "Ŝţřĭĸĕŧĥŕőŭģħ",
      "SuperscriptButtonLabel": "Śųƥęŗşćŕĩƥţ",
      "SubscriptButtonLabel": "Šűɓšćŕıƥţ",
      "ParagraphGroupText": "Ƥåŗäĝřáƿĥ",
      "JustifyButtonLabel": "ĵůşţĩƒɏ",
      "IncreaseIndentButtonLabel": "Īŉčŕěäšė įńđĕņţ",
      "DecreaseIndentButtonLabel": "Ɗēĉřęâśȅ įŋđęŋţ",
      "FontSizeDropDownLabel": "Ƒŏŋţ ŝĩžĕ",
      "TableTitle": "ŤȃƂļȇ",
      "TableGroupLabel": "ŤàƂĺē (Ƥřēvıěŵ)",
      "TableGroup": "ŦąƄļĕ",
      "TableButtonLabel": "Įņśȅŕť ŧåƂļĕ",
      "InsertAndDeleteGroupLabel": "Īŉşȇŕŧ ãňđ ďěŀęťē",
      "InsertRowBeforeButtonLabel": "Ĭņśēřţ ăƅōvę",
      "InsertRowAfterButtonLabel": "Ĭńŝēŗŧ ɓėļơŵ",
      "InsertColumnLeftButtonLabel": "Įņşȅŕţ ĺȇƒŧ",
      "InsertColumnRightButtonLabel": "Ĩŋšěŕť ŕįğĥţ",
      "DeleteRowButtonLabel": "Ɖęłēţė ŕōŵ",
      "DeleteColumnButtonLabel": "Ďȇľēŧȇ ċőļũmŋ",
      "DeleteTableButtonLabel": "Ɖĕŀȅŧȅ ťáƂĺē",
      "FontColorLabel": "Ƒŏņŧ ċōĺơŕ",
      "StandardColorLabel": "Ŝťàƞďǻŕď ĉơłơřš",
      "DefaultColorLabel": "Ăũťŏmáţįć",
      "RedDarkLabel": "Đäŗķ ŗēđ",
      "RedLabel": "Ʀȅđ",
      "YellowLabel": "Ÿěłŀōŵ",
      "GreenLightLabel": "Ŀĩģĥţ ġřēēņ",
      "GreenLabel": "Ģŗėěŋ",
      "GreenDarkLabel": "Đāŗķ ġŕėėŉ",
      "BlueLightLabel": "Ļĩģĥť ƅŀűȅ",
      "BlueLabel": "Ƀŀūę",
      "BlueDarkLabel": "Ɖàřƙ ɓŀũė",
      "PurpleLabel": "Ƥŭŗƿŀě",
      "HightlightLabel": "Ħīĝĥĺĭģħţ ĉơļŏŗ",
      "HightlightColorsLabel": "Ħįĝħŀĭĝĥť ćơłơŕś",
      "PinkLabel": "Ƥīńķ",
      "OrangeLabel": "Ơřàńğĕ",
      "RemoveHighlightColor": "Ņō čōľơř",
      "HyperlinkGroupLabel": "Ħȳƥēŗĺıņķ",
      "TealLabel": "Ŧȅȃł",
      "MagentaLabel": "Mâĝęŋťä",
      "AquaLabel": "Āǫūâ",
      "MaroonLabel": "Mȃřŏōņ",
      "GoldLabel": "Ģơľď",
      "GreyLabel": "Ĝřěŷ",
      "DarkGreyLabel": "Ďȃŕƙ ġŗĕȳ",
      "BlackLabel": "Ɓłǻċĸ",
      "ThemeColorGroupLabel": "Ŧĥėmė ċŏļŏŗš",
      "ThemeDarkerLabel": "Ťĥĕmȇ đâřĸěř",
      "ThemeDarkLabel": "Ťħȇmė đǻŕķ",
      "ThemeDarkAltLabel": "Ťħėmę đâřƙ āŀťěŕńâţȅ",
      "ThemePrimaryLabel": "Ťĥȅmĕ ƿřīmăŗȳ",
      "ThemeSecondaryLabel": "Ŧĥěmȅ ŝęčőńđåŗƴ",
      "NeutralDarkLabel": "Ņęŭťřȃļ ďåřĸ",
      "NeutralPrimaryLabel": "Ŋȅũŧŗąĺ ƿŗīmåřȳ",
      "NeutralPrimaryAltLabel": "Ŋėűťŕāĺ ƿŕįmȃřɏ ȃľţėŗƞąţĕ",
      "NeutralSecondaryLabel": "Ɲęűŧřăŀ šęčőňďȁřɏ",
      "NeutralTertiaryLabel": "Ŋȇůťŗăŀ ţěřťīāŕȳ",
      "TableStylesGroupLabel": "Ţáƀļē şţŷŀėš",
      "SimpleTableButtonLabel": "Ƥĺȁīń",
      "TableWithHeaderBorderLabel": "Śųƅťŀė ħȇāđēŕ",
      "TableWithFilledHeaderLabel": "Ĥěāđȇŗ",
      "TableWithBandedRowsLabel": "Åĺťĕŗŋăţĩŉğ řōŵş",
      "TableWithBandedRowsAndColumnsLabel": "Ćŏŀūmń ĥěäđėŗ",
      "SimpleTableButtonThemeLabel": "Ŧħēmȇ-ćőĺōřēđ ƿłāīƞ",
      "TableWithHeaderBorderThemeLabel": "Ťħēmȇ-ćōļơřěď ŝūƀťľȅ ĥĕáđěŗ",
      "TableWithFilledHeaderThemeLabel": "Ŧħȅmĕ-ĉōłōŗěď ĥėȁđȇř",
      "TableWithBandedRowsThemeLabel": "Ťĥęmė-čōłŏŕęď âŀŧȅŕńȁŧīŋġ ŗŏŵş",
      "TableWithBandedRowsAndColumnsThemeLabel": "Ŧĥėmȇ-ćơŀōŗěđ čőłůmƞ ħĕåđȅř",
      "AlignTableGroupLabel": "Ŧâƅłė áŀĭĝŋmĕńŧ",
      "AlignTableLeftLabel": "Ăľįġņ ţāɓłę ŀȅƒť",
      "AlignTableCenterLabel": "Ȃľĭġƞ ťäƂľě čęŋťȅŗ",
      "AlignTableRightLabel": "Äľĭġň ţàƂŀě řĩĝħŧ",
      "RTEPagePickerSaveAction": "Ŧħę ĺĭņƙ {0} ĩş äďďȅđ.",
      "RTEPagePickerUnlinkAction": "Ťħė łĩńƙ {0} īş ŕęmōvęď."
    },
    "_jP9TaPNRkCXWU4OplNcN+w": {
      "AriaWebPartOrSectionEnterTemplate": "{0}. Ƥŕȅşş Ęŉŧěř ŧơ ńăvıģȃťė įŉşĩďė ŧĥȇ {1}. Ŵĥȅŉ ıņšīďė, ŭšę Ȁļť+Ƒ10 ťŏ ġő ţō ŧơŏŀɓåŗ, ūŝȇ Ąŀŧ+Ƥ ťō mōvē ƒơĉūš ŧơ ŧħě ƥřơƿēřťɏ ƿȃńė āňđ ūśė Ęšċåƥȇ ťơ ȅxįť ťħę {1}.  ",
      "CanvasZoneAriaGoToToolbar": "Ƥřĕśś ēƞŧȅŕ ŧŏ ƒőĉűŝ ıƞşįđĕ ťħę ŵȅɓ ƥąřť. Āƒťēŕ ŷŏŭ äŗě ĭń ťĥė ŵěɓ ƿãŕţ, ƿŕēśş ĕŝćäƿė ţő řęţůŕņ ťő ŧĥę ŧơőłƂăŕ.",
      "CanvasZoneAriaGoToWebPart": "Ƥřěśś ęņŧȅř ťơ ġő ŧō ťĥĕ ŵěƃ ƥāŕť'ŝ ŧơőĺƂâŗ, ȳơű čàƞ ťħēŋ ƥřėŝŝ ėşċåƿě ţō řěŧũřŉ ħěŕę.",
      "CanvasZoneAriaWebpartName": "{0} Ŵěƅ Ƥâřť",
      "ConfirmationDialogYes": "Ÿěś",
      "ConfirmationDialogNo": "Ňơ",
      "DeleteZoneConfirmationDialogMessage": "Äřē ɏōų şŭřĕ ƴơū ŵäƞť ţơ ďěłęťē ťĥĭş śȅćţįőň ȃńđ ȇvēŗɏţĥīŉĝ īƞ īţ?",
      "DeleteConfirmationDialogTitle": "Đĕľęţė Ċŏŋƒıŗmåťıőŉ",
      "DeleteConfirmationDialogMessage": "Áŗĕ ȳŏū şűŕė ȳőū ŵąņŧ ŧō ďȇĺĕŧē ţħīś ŵȅƄ ƥȃŗť?",
      "TextWebPartPlaceholder": "Ťɏƿĕ ƴōūŕ ťėxţ ħęŕė",
      "TextWebPartDisplayName": "Ŧȅxť",
      "TextWebpartDescription": "Ăđď äŉđ ƒőřmăť ŧēxť.",
      "WebpartToolbarConfigButtonTitle": "Ēđįŧ ŵĕƅ ƿȃřŧ",
      "ZoneToolbarConfigButtonTitle": "Ěďĩť ŝȅĉťıŏņ",
      "WebpartToolbarMoveButtonTitle": "Mơvė ŵĕƂ ƿãřť",
      "ZoneToolbarMoveButtonTitle": "Mŏvę śēćťĩőƞ",
      "WebpartToolbarDeleteButtonTitle": "Ɗĕłėťȇ ŵěƀ ƥàŗţ",
      "ZoneToolbarDeleteButtonTitle": "Đěĺȇţȇ šȅčŧīōŋ",
      "ToolbarNavigationArrowKeys": "Ůşȅ ǻŕŗơŵ ĸēƴś ťő ńăvĭĝãŧę ĩńśīđė ţħĕ ŧŏơłƃăŕ.",
      "ToolboxAriaLoadingAlert": "Ţħȇ ţōơļƀōx ĩş ļőȁđıŉĝ ŵěƄ ƥâřŧş.",
      "ToolboxAriaLoadingFinishedAlert": "Ŧĥė ťŏŏĺƃōx ƒĩŋīŝħēđ ŀőåďıņĝ ŵȇƄ ƥȃŗťŝ.",
      "ToolboxErrorMessage": "Ťĥȇŕȅ ŵăš ȁń ȅŗřőŗ ƒęŧċħĭńĝ ţĥė ŵĕƀ ƿåŗţŝ. Ņōţ ȁłľ ŵěƄ ƿáŕŧš mâƴ Ƅė âvâįľäƃłȇ.",
      "ToolboxHintTitle": "Àđď à ŉĕŵ ŵęɓ ƥȃŗţ",
      "ToolboxNavigationArrowKeys": "{0} Ūşę Ĺėƒţ ơŕ Řĭģĥť ţơ ŉàvĩğąţȇ. Űşė Ěńťęř ŧŏ ǻđď ţħĕ ŝȇľēčŧȅđ ŵěƂ ƥãřţ.",
      "CanvasItems": "{0} ĭţȇmŝ īŋ ťħē ŧŏōĺɓȃŕ.||{0} ıťěm īń ţħę ŧơơłɓǻř.||{0} īŧėmŝ ĭƞ ŧħȇ ţŏơľƅãŕ.",
      "CanvasItemsInterval": "0||1||2-",
      "ToolboxSectionHeader": "Şȇčŧīōń ŀãŷơűŧ",
      "ToolboxOneColumnPart": "Ŏŋĕ ċơłūmň",
      "ToolboxTwoColumnPart": "Ŧŵơ ĉŏŀůmŉś",
      "ToolboxThreeColumnPart": "Ŧĥřěȅ ćōľũmņş",
      "ToolboxOneThirdRightColumnPart": "Ōƞē-ţĥīŕđ řĭĝħţ ćơŀŭmƞ",
      "ToolboxOneThirdLeftColumnPart": "Ōņě-ţħīřđ ļēƒţ čơľųmň",
      "ToolboxFullWidthColumnPart": "Ƒŭŀŀ-ŵīďţħ ċőĺũmŉ",
      "ToolboxVerticalColumnPart": "***Vęřŧįćąŀ ċōłŭmņ",
      "ToolboxVerticalColumnToolTipText": "***Čāƞńơť āđđ vėřťĩĉàĺ śęćţĭōņ ƀēćȃűšȇ ȇıţĥȅŗ vēřťĩćàľ śėčťĭōň ŏŗ ƒũļľ ŵıďŧħ śęćŧįŏņ åłŗȅáđƴ ĕxīśŧş",
      "ToolboxFullWidthColumnTooltipText": "***Čáňńŏţ ȇđīť ƒūłĺ ŵĩđťħ šěĉŧıơŋ ɓȅĉăűŝę věřťıċāĺ şȅĉŧĩőŋ ĕxıŝţś",
      "SectionPropertyPaneTitle": "Şȅĉťıōŋ",
      "SectionPropertyPaneColumnGroupName": "Łâƴơūţ őƿťĩōņş",
      "ToolbarSelectZone": "Śȇŀęčŧ šĕĉťīŏň",
      "DragIconFallbackRTEText": "Ţēxť",
      "DragZoneHandleTitle": "Ƥřȇšş Ȅƞťěŗ ŏŕ Ŝƿàĉē ŧő ȅŉţĕŗ mōvĕ mŏďė",
      "DragZoneMoveStarted": "Ƥřȇśŝ ůƿ ãŕřőŵ ĸȅŷ ťő mővę ūƿ àŉđ ďŏŵŉ ãŗřŏŵ ķęɏ ţō mơvȇ ďŏŵŉ. Ƥřěşŝ Ĕƞťēŗ ŧō ĉơŋƒĭŕm ŧħȇ mōvě. Ƥŕēŝś ęśćȁƿę ŧŏ čãŋčĕĺ ŧĥȇ mŏvē. ",
      "DragZoneMoveComplete": "Mŏvēđ ŵȇƅ ƥàŗţ ƒŗŏm {0} ťō {1}. ",
      "DragZoneMoveCompleteZone": "Mővĕď śēčţīơń ƒřōm {0} ťō {1}",
      "DragZoneMoveCancelled": "Mơvė ĥãš Ƅȇęŋ ćäŋćęļľȅđ.",
      "DragZoneMoveNotAllowedAriaLabel": "Čąň'ť mŏvę ȃńƴ ƒűřŧĥēř ĭņ ŧĥǻţ đĩŗȅčŧıơŋ, ŏŕ mŏvȇ įş ŉőť ãłľơŵēď ŧō ţĥāť śěĉŧıŏň",
      "DragZoneMoveNotAllowed": "Mŏvē ńōŧ ǻŀĺōŵȇđ",
      "DragZoneMoveInsideLevelControl": "Ƥőśīŧįơŉ {0}",
      "DragZoneMoveInsideLevelSection": "Ċőľųmň {0}, ƥŏşıťįōņ {1}",
      "DragZoneMoveInsideLevelZone": "Šėĉŧįōń {0}, čōŀŭmƞ {1}, ƿőŝĭţīōŉ {2}",
      "WebPartAriaLabel": "ŵȅƄ ƿāřť",
      "SectionContextualAriaLabel": "{0}, {1} ŝȅċţįơŉ ĉơŋţăĭńįńģ {2}",
      "SectionAriaLabel": "šęĉŧıōń",
      "WebPartsInSectionLabel": "{0}, {1}",
      "ToolboxHintSectionTitleOnlyLayouts": "Áđđ å ƞȇŵ šěċŧīŏņ",
      "ToolboxHintTitleWithLayout": "Àđđ ä ŋěŵ ŵėƂ ƿȃřť ıń {0}",
      "ToolboxHintColumnOne": "ċōĺũmņ ōņę",
      "ToolboxHintColumnTwo": "ćơłŭmň ţŵơ",
      "ToolboxHintColumnThree": "ċŏłŭmņ ťħŗȅė",
      "EmptySectionAriaLabel": "ŉơ ŵėƃƿàřţ",
      "SectionPositionAriaLabel": "Śĕćŧįŏŋ {0} ōƒ {1}",
      "CloseButtonAriaLabel": "Ĉļơŝė",
      "DeleteConfirmationLabel": "{0} ħǻš ƃėȅń đȇľěťęď.",
      "NarrowModeDialogTitle": "Ŵĩđȇŉ ŷơũŗ ƅŗŏŵşĕŕ ŵĭŉďōŵ",
      "NarrowModeDialogSubtitle": "Ēďıťıŋģ ıš ňőţ åvàįļàƀļē īņ ȁ ņǻŗŗŏŵ ƃřōŵŝēŕ ŵīƞďơŵ. Mȁĸę ťħĕ ŵĩńďơŵ ŵıďĕř ţơ ćŏŋţįŉūę ēďīťĩňĝ.",
      "DialogDescription": "{0} ďĭȁŀőĝ {1}",
      "SectionBackgroundPropertyColumnGroupName": "Šěĉŧĩơň ƀāċķğřŏųńď",
      "SectionBackgroundNeutralButtonLabel": "Ńęűťřåľ",
      "SectionBackgroundSoftButtonLabel": "Šơƒŧ",
      "SectionBackgroundStrongButtonLabel": "Ŝťŕơŉġ",
      "SectionBackgroundNoneButtonLabel": "Ŋŏņė",
      "CanvasVerticalSectionZoneLabel": "***Věŕťıčąĺ Ŝȇčţįőń 1 őƒ 1",
      "ToolbarDuplicateTitle": "Ďůƿĺıĉāťȇ ƿäŗť",
      "YammerHighlightsWebpartTitle": "Ħĭġĥłĩġħŧš"
    },
    "_O6tJrUs6NrlW91qKLBlc7g": {
      "loadingText": "Ļōąđįŋğ…",
      "relevantPeopleHeaderText": "Ƥěơƥŀė ȳơű ŵőřĸ ŵīţħ",
      "noResultsFoundText": "Ŵȇ đĩďň'ť ƒıńď ąńȳ màţċħěś",
      "suggestionsAvailableAlertText": "Šũğġȇŝťįőņś ąvāīŀàƀľė",
      "suggestionsContainerAriaLabel": "Şůĝĝĕŝťȇđ ćŏƞţȃĉťš",
      "suggestionsHeaderText": "Şűģģēśťįőńś",
      "moreCharactersText": "Ęńţȇŕ mōřȇ čħãřǻĉŧȇŗš",
      "noPermissionText": "{0} đőēš ņōţ ĥàvě ƿȇŕmıśşıŏń ťő ţħĭš ƿãğȅ, šŏ ŵĭĺł ňŏţ ƃȅ ņōţıƒĩĕđ ǻƀōůť ɏơůŕ ċőmmȅńŧ.",
      "mentionLink": "@{0}",
      "teachingBubbleHeadline": "@Męňţįŏŋ",
      "teachingBubbleContent": "Ȳőŭ ćāń @mėƞŧįōŉ ƥȅơƿļě ıň ĉőmmȇņţŝ ŵħęň ɏőŭ ŵàńť ţő ĝėţ ťĥěĭř àŧťȅŋťĭơń. ĵųšŧ ţȳƿē ŧĥě @ şɏmɓŏł Ƅēƒőŕȇ ā ŋãmę ţŏ ğĕŧ ŝţáŕťȇď!",
      "mentionPlaceholderText": "{0}. Ŧƴƥȅ @ ťō měņţıőŋ šōmęőńę",
      "CloseButtonAriaLabel": "Ċĺơšȇ",
      "searchDirectory": "Šėăŗċħ ďĩřȇċŧōŗƴ",
      "mentionAlertMessage": "Mĕńŧįơň àđďȇď ƒơŕ {0}"
    },
    "_/GZrHjuQO4erDQbBRI2XSA": {
      "DialogTitle": "Ĭńşėřţ ĺīńķ",
      "UrlTextFieldLabel": "Ȁďđŕĕşš",
      "UrlTextFieldAriaLabel": "ŴęƂ ãđďřěśš ŧŏ ŀıƞĸ ţơ",
      "UrlTextFieldError": "Ţħĩš łıņķ ŧȳƿě ĩŝ ńŏŧ šũƿƿőŕťȅď.",
      "TitleTextFieldLabel": "Ţĕxţ ťō ďįšƥļãƴ",
      "RecentPagesLabel": "Mơŝť ŕėċȇƞŧ ƥåģȇŝ ŏň ťħįŝ šĭţȅ",
      "SearchForPagesLabel": "Ƥâğȇş ōŉ ťħĭŝ şĩťȅ ŧħãŧ mǻťĉħ ɏŏųŗ šėâŕćħ",
      "RecentSpacesLabel": "***Mőŝţ ŕėčēńŧ şƥȁċęš ōƞ ŧħĩŝ şįťě",
      "SearchForSpacesLabel": "***Ŝƿåćęś őņ ŧĥıś šĩţȇ ţĥąŧ mȁţĉħ ɏőŭŕ şěǻŕćĥ",
      "NoResultLabel": "Ɲơ ĩťĕmş máŧċĥ ŷőũŗ ŝēȁřĉĥ",
      "TryAgainLabel": "Ťŗƴ ä ďįƒƒěŗěŉť ƙȅɏŵōŗđ",
      "OpenLinkInNewTabLabel": "Őƿēŉ ŀįƞĸ ĭň ǻ ňēŵ ţȃƀ",
      "SaveButtonLabel": "Ŝävē",
      "CancelButtonLabel": "Ĉåňćĕļ",
      "UnlinkButtonLabel": "Řȇmōvė ŀıņĸ",
      "TitleSuggestionsColumnName": "Ťīťłė",
      "EditorSuggestionsColumnName": "Mŏđĭƒıēď ƃƴ",
      "ModifiedSuggestionsColumnName": "Mōđįƒıėď",
      "PageContentContainsSearchText": "\"{0}\" ƒōũņď īŋ ƥȃġĕ ĉŏňŧȇƞţş",
      "CurrentPage": "(ċųŕŕĕńţ ƥäĝĕ)",
      "SearchTextFieldLabel": "Šȅăŗćĥ",
      "SearchPagesTextFieldPlaceholder": "Ȇŉŧȇŕ ƙȇŷŵŏřďš ťō şėãřćħ ƒŏŗ ƥãĝȅś ơń ţĥįŝ ŝıťė",
      "SearchSpacesTextFieldPlaceholder": "***Ēŋţěŕ ķȅɏŵōŕďŝ ŧō ŝēǻřċħ ƒőř šƥȁčȅš ŏņ ŧħīś śīťĕ",
      "DialogAriaDescription": "Ĩŉśȇŕť ä łĭńƙ ŧơ ą ƿȁğȅ ōŉ ťĥě ċũŕŗęŋť šĩŧę őŕ ťō à ƥāġȅ ŏň ȃńōŧħȅŗ ŝıŧȅ.",
      "SuggestionsListAriaLabel": "Śėĺėčŧ à ƿǻĝě ƒŗōm ťħȇ {0} ĺĩšţ. Ƥŗȇşş ţħĕ Ūƥ ãńđ Ďŏŵň ȃŗŗőŵ ķȅƴś ťő ƞâvįğǻťě ŧĥřōůģħ ŧĥĕ ƿȁġėš. Ƥŗēŝş ŧħȇ Šƥáċĕ ķȇɏ ťő şȇļȅćţ ä ƥăğę. Ŵħěň á ƥãĝĕ įś šęĺĕćţėď, ţħě ƿáĝę ľīƞĸ ŵıłŀ ɓė ūšěđ ĭŉ ťĥė Ļıńķ ıŋƥūť ƀőx, āņď, īƒ ţħēřē ĭŝ ŋō ŧęxť īƞ ţĥě Ţĕxŧ ŧŏ đĩšƿłãŷ įņƿūţ Ƃŏx, ţĥę ƿãģȇ ŧĭţĺě ŵīŀĺ Ƃĕ ūşȇď.",
      "SaveButtonDisabledScreenReaderAlert": "Ŧĥě Ŝâvĕ Ƃűţŧőŋ įš ņőť àvǻĩľāɓļě Ƃȇčåűśȅ ȃŋ īŋvąłĭđ ŵĕƀ àđđŕȅŝš ŵåş ĕńŧȇřėđ.",
      "SaveButtonEnabledScreenReaderAlert": "Ţħě Śąvē Ƃůŧŧŏŋ įş ȁvąīľäƃŀē.",
      "PageIsSelectedScreenReaderAlert": "Ţĥē ƿäĝȇ {0} ıŝ ŝęłȇċŧěď.",
      "IsSearching": "Şȇàřčħįņĝ...",
      "SearchResultsShowing": "Ŝȅȁřĉħ řȇşůľţş äŕė đįŝƿŀäɏėđ. Ƥřĕşŝ Ŧăƀ ţơ ğő ţŏ ŧĥė Šȅȃŗćħ řĕşųľťś ļīšť.",
      "RecentPagesShowing": "Ā ļīšť ōƒ ŗēĉȅņţ ƥäĝęŝ ĭś đĭŝƥłāȳĕđ. Ƥŕȇśš ŢåƂ ţơ ġō ţơ ťħȇ Ʀėċȇņť ƥåğęś łĭšŧ."
    },
    "_4SOrKBlkyRLkXWcT6txoow": {
      "ToolboxSearchAccessibleLabelTemplate": "Ţɏƥĕ ĥėřē ţő şȅàŕćħ ƒōŕ ą ŵēƄ ƥàŕť. {0}",
      "ToolboxSearchEscapeAccessibleLabel": "Ƥřĕŝš Ęşčäƿȅ ŧő ćľĕãř ŧĥě ȅxĩşťįƞģ šęāřċĥ.",
      "ToolboxSearchLabel": "Şėåřĉĥ"
    },
    "_NS+5Kf9zpnH1/LStsp+Tfw": {
      "ToolboxCategoryTextMediaAndContent": "Ŧĕxť, mėđĭâ, äńđ čơńţěŋţ",
      "ToolboxCategoryDiscovery": "Ɗīśćơvēŕȳ",
      "ToolboxCategoryCommunicationAndCollaboration": "Ĉōmmūńįĉąŧįŏņ ȃņď čōŀŀãƃōŗäťıōņ",
      "ToolboxCategoryPlanningAndProcess": "Ƥłǻńńĩňģ àŋđ ƿŗōćėşś",
      "ToolboxCategoryBusinessIntelligence": "Ɓůśįńěšŝ āŋď īńţȅľļįġęňċȅ",
      "ToolboxCategorySiteTools": "Şĩŧė ŧōơĺš",
      "ToolboxCategoryConnectors": "Ċőŋňěċťŏŗś",
      "ToolboxCategoryOther": "Ŏťħēŕ",
      "ToolboxGroupNameFeatured": "Ƒȇȃťůřěď",
      "ToolboxGroupNameAlphabetical": "Āĺŀ Ą ţŏ Ż"
    },
    "_RRzf46hnc4+fBX8RHyocNg": {
      "TextWebPartDisplayName": "Ŧȅxţ",
      "TextWebpartDescription": "Àďđ äńď ƒōŕmȃť ŧēxŧ"
    },
    "_6tOZemhV08aF1IgNDNeiwQ": {
      "ToolboxGroupNameFullWidth": "Ÿōų ċăņ ãđđ ŏńȇ ŏƒ ţĥēśě ŵęƂ ƥāŕťš ŧơ ťħįŝ ƒūļļ-ŵıďŧĥ ċŏļůmņ"
    },
    "_2TT4IG31kAjRqhD0h5kPOg": {
      "ToolboxGroupSeeAllButtonLabel": "Ŝęȇ äľł",
      "ToolboxGroupSeeAllButtonAriaLabel": "Šȅě ǻłľ ŵęƃ ƥǻřŧś ıƞ {0}.",
      "ToolboxGroupAriaLabel": "{0} ļĭšţ. Ŭšě ľĕƒţ ãŉď řıĝĥţ ȁřŗŏŵ ĸěƴş ťő mővě ŵįťĥıň ťħė ľıśŧ."
    },
    "_WVn4QXYnL8WpGCqr2C9ySA": {
      "ToolboxCategoryAllCategory": "Áĺŀ ƀɏ ćȃţĕģőřƴ",
      "ToolboxCategorySortingCategory": "Ãļļ Ā ŧŏ Ž",
      "ToolboxCategorySearchResults": "Šęåŕčħ ŕȅšůŀŧš",
      "ToolboxCollapseButtonDescription": "Řęŝťőŗě ťŏ ŏŗĭġĩƞāľ ŝīžė",
      "NoResultLabel": "Ńō ĩŧĕmş māţčĥ ŷŏůř šěăřćħ",
      "TryAgainLabel": "Ţřƴ ä ďĩƒƒęŗěƞť ƙĕȳŵŏřď",
      "LargeToolboxAriaTitle": "Ĕxƿȁňďȅđ ŵȅƅ ƥäŕť ŧŏŏłɓơx.",
      "LargeToolboxAriaSubTitle": "Ťĥȇřę ȃŕȅ {0} įťȇmš ĭņ ŧĥȅ ŧőőŀƃơx.||Ŧĥēŗȇ áŗē {0} īťęm ĩň ťĥę ťơơļƅơx.||Ţħěřě åřĕ {0} įţĕmś īŋ ťĥĕ ťőŏĺƄŏx.",
      "ToolboxCollapseButtonAriaLabel": "Ċőŀłăƿşȇ.",
      "CountStringIntervals": "0||1||2-",
      "DropDownMenuAriaLabel": "Ŝĥơŵĭņġ ŵȇƅ ƥąřťš ƒŕōm {0} ćàţěğőŕŷ.",
      "SwitchCategoryAlert": "Ćħäŉġęđ ţŏ {0}.",
      "BackButtonAriaLabel": "Ģŏ ƀȃĉƙ ŧŏ ţĥȅ ƥŗĕvĭōŭŝ vīȇŵ."
    },
    "_CZsUWMvZilAKKAfwQSdzKQ": {
      "ToolboxExpandButtonTitle": "Ęxƿáńď ţŏ śęē mŏŕę ŵėƄ ƿāŗťš",
      "ToolboxNoItemsFound": "Ŵė ċơũłđň'ť ƒıńď ãňƴťħĭŋĝ ţĥȁţ mãŧćħȇš ŷơűř śěąřćħ.",
      "ToolboxSectionHeader": "Šȅčŧįŏŋ ľąƴơūŧ",
      "CanvasItems": "{0} ŵēƀ ƥāŕťś ďĩśƿŀàŷĕď ĩń ţĥȅ ťŏőŀƄơx.||{0} ŵęɓ ƿåŗţ ďįŝƥŀǻɏȇđ įņ ţħē ŧŏőľƅơx.||{0} ŵėƄ ƿäŕŧŝ đįŝƥļȃƴēđ īƞ ťħē ťơŏļƄơx.",
      "CanvasItemsInterval": "0||1||2-"
    },
    "_NAR8NFw8cblGJm9t5CjqOw": {
      "SuccessfullyLoadedText": "Ŝųċĉēśŝƒųļľƴ ŀőăđěđ đĕƃűģ máƞīƒęśťś.",
      "ErrorLoadingText": "Ƒǻıļēď ţō ŀŏȃď ďěƂűġ mäňıƒęšţš: {0}"
    },
    "_vd/LT/qfiQhbHFfeM1GtlA": {
      "FetchFailedError": "***Ƒȇťčħĭŋğ ŵȇƄƥȁţŝ ƒȃĩļȅď ŵıťħ ȅřŕōŕ \"{0}\". Ʀęňđȇŗ őƒ á ċàĉħęď ŵōŕķƂȇňćħ måȳ ƒãĩľ."
    },
    "_FQya7ZjwIyrOEutOa+omIA": {
      "Title": "Ŵâŕňĩƞĝ",
      "SubText": "Ƴōűŕ ŵĕƄ ƿȁŕŧ ŵĩļŀ ňőŧ ǻƿƿēåŕ ĩň ţħē ţőōļƃơx. Ƥľēāśĕ mȃƙĕ şůřĕ \"ġűļƥ śĕřvě\" ış ŗůŋņįŉġ īŉ ã ŵēƂ ƥāřţ ƥŗōĴēćŧ. Ƥļęāśė ŕėƒŕěšħ ţħȇ ƥąģȇ ōňĉȅ \"ğųŀƥ śěřvȇ\" ĭś řŭŋƞįŉģ.",
      "OkButtonText": "ƠĶ",
      "ClickHerePrefix": "Ćļıćĸ ",
      "ClickHereLink": "ħėŕȇ",
      "ClickHereSuffix": " ƒōř mōŕě įńƒōŕmãţıơņ."
    },
    "_1JArBGDet5Uj9pJOV/9sFw": {
      "UrlTextBoxPlaceholder": "Ěŋŧėŕ ā ŮƦĻ ťō vįȅŵ ĭŋ Mŏƀĩłȅ Ƥŗēvĭȅŵ Ŧőŏľ.",
      "ScreenReaderMobilePreviewEntered": "Ƴōū ħåvė ęńťėřȇđ ţħȇ Mơƃīļȇ Ƥŕěvīȅŵ Ŧơőŀ. Įƒ ƴőū ŵâŉţ ţō ƥŗēvĭĕŵ ǻ đįƒƒĕŗėńţ ƿáĝė, ēňţȇŗ ťħě ŮŔĻ ıŉ ŪŔĿ ţėxŧ ƒĭęłđ. Ŧō ĉĺōšē ŧħē ţōőļ ȁňď ģŏ ƅàćƙ ţō Ŵōŗĸƅȅņĉħ, ƥŗȇśŝ Ęśčǻƿě.",
      "ScreenReaderDevicePickerEntered": "Ūšę łęƒť ăŉď ŗįĝĥŧ ǻŕŕőŵ ĸȅŷš ŧō čħŏŏşĕ ą đěvīčȅ ŧơ ċĥáňğȅ ťĥȇ ƿŕėvıĕŵ šćŕēěň şīƶȅ.",
      "ScreenReaderDevicePickerSelectionChanged": "Ƥřĕşŝ Ĕņţēŕ ťŏ čħőŏšě ţĥıŝ đěvıćė.",
      "Width": "Ŵĩđţĥ",
      "Height": "Ħēīğĥţ"
    },
    "_8EVKOH1av6NjR/ZNfdafrw": {
      "WebPartData": "***Ŵēƅ Ƥářť Đȃŧå",
      "ClassicPages": "Ćĺȁśśīċ Ƥȃĝȇś",
      "ModernPages": "Mōđēřŋ Ƥàġęş",
      "Close": "Ċĺőśę",
      "WebPartDataHelpInfoLink": "***Ŀęãŕŉ ąɓŏũţ ƥřōvįŝĩơņıņģ ŞħãŕęƤŏįňť ǻšŝěťŝ ƒŗőm ŷőũř ŚĥǻŗēƤőĩŋŧ ċļīȇňť-ŝīđė ŵēɓ ƥăŗť"
    },
    "_IusqdbcSoVYQiit3+QRSxw": {
      "Office365Title": "Őƒƒīĉȇ 365",
      "SharePointWorkbenchTitle": "ŚħãŗěƤőĩƞţ Ŵōŕĸƅȅńćĥ",
      "ScreenReaderDisplayModeSwitchToEditMode": "Şŵįţĉĥȅđ ƒřơm ƿřēvĩȅŵ mơďę ťŏ ĕđįţ mōđȅ.",
      "ScreenReaderDisplayModeSwitchToReadMode": "Şŵĩťċĥęď ƒŕŏm ęďĩţ mơđĕ ţơ ƿŗēvıěŵ mơďė."
    },
    "_nCtJlVOXBHa59LgYtajnjA": {
      "Save": "Ŝȃvę",
      "SaveAltText": "Ũŝȇ ţō šávě ţħē ĉūŗřȇƞť ŵōřĸƅěňčĥ šŧàţĕ.",
      "Discard": "Ďīşčåřđ",
      "DiscardAltText": "Ųŝě ţơ đīşčàŕđ ŧħȇ ĉũŕŗȅƞŧ ŵŏřƙƂėňčħ şŧáŧę.",
      "Mobile": "Mőƃīļȅ",
      "MobleAltText": "Ůšȅ ŧő ơƿěņ ťĥȅ mơƂįŀȇ ƿŕėvįĕŵ ťőōŀ ƒơř ã čȅļľ ƥĥōŉĕ.",
      "Tablet": "Ţăƃĺěť",
      "TabletAltText": "Ūśė ťō ơƿěŋ ţĥė mŏƂĩŀȅ ƿřȅvīēŵ ťơōļ ƒŏŕ ā ťǻƄļēţ.",
      "Preview": "Ƥŕėvıȇŵ",
      "PreviewAltText": "Ũŝė ťő śŵĩťċħ ƒřőm ęďĩť mōďȅ ţő ƿřȅvīęŵ mơđĕ.",
      "Edit": "Ěđįţ",
      "EditAltText": "Űšę ŧơ şŵıťĉħ ŧō ēđĩţ mőđĕ.",
      "WebPartData": "***Ŵĕƃ ƿȁřť ďáţǻ",
      "WebPartDataAltText": "***Ďĩśƥłăƴ ţĥě ŝęŕĭąłĩžēď ŵȅƃ ƿåŗŧ ďāŧȃ."
    }
  };

  strings.default = strings;
  return strings;
});